# Generated by Django 5.1.1 on 2024-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='grade_admitted',
            field=models.CharField(choices=[('GRADE_ONE', 'One'), ('GRADE_TWO', 'Two'), ('GRADE_THREE', 'Three'), ('GRADE_FOUR', 'Four'), ('GRADE_FIVE', 'Five'), ('GRADE_SIX', 'Six'), ('GRADE_SEVEN', 'Seven'), ('GRADE_EIGHT', 'Eight'), ('GRADE_NINE', 'Nine')], default='GRADE_ONE', max_length=30),
        ),
    ]
